const historyData = [
  {
    idHistory: 1,
    title: "Hồng Bàng & Văn Lang",
    description:
      "Thời kỳ Hồng Bàng theo truyền thuyết và dã sử cho rằng bắt đầu từ năm 2879 TCN, là niên đại của Kinh Dương Vương, với quốc hiệu Xích Quỷ. Lãnh thổ của quốc gia dưới thời Kinh Dương vương rộng lớn, phía bắc tới sông Dương Tử (cả vùng hồ Động Đình), phía nam tới nước Hồ Tôn (Chiêm Thành), phía đông là Đông Hải (một phần của Thái Bình Dương), phía tây là Ba Thục (Tứ Xuyên, Trung Hoa ngày nay). Về sau người Việt chỉ thấy có ở miền Bắc Việt Nam ngày nay, có thể một phần do sự lấn áp của các tộc người Hoa Hạ từ phương Bắc.\n\n Có ít nhất 18 đời Hùng Vương cai trị trong thời đại Hồng Bàng, cho đến năm 258 TCN. Các thông tin về các đời vua Hùng dựa nhiều trên các truyền thuyết. Cũng có nhiều bằng chứng khảo cổ học như trống đồng Đông Sơn được tìm thấy ở miền bắc Việt Nam có cùng niên đại với thời kỳ Hồng Bàng, thể hiện một nền văn hóa đồ đồng rất phát triển (văn hoá Đông Sơn).",
    subTitle1: "Kỷ Hồng Bàng Thị",
    description1:
      'Theo truyền thuyết thì thủy tổ dân tộc Việt Nam là Kinh Dương Vương, hiện còn có mộ tại làng An Lữ, Thuận Thành, Bắc Ninh. \n\n Kinh Dương Vương làm Vua vào khoảng năm Nhâm Tuất (hơn 2000 năm trước Công nguyên). Kinh Dương Vương lấy con gái Thần Long là Vua hồ Động Đình sinh một con trai đặt tên là Sùng Lãm, sau nối ngôi vua cha niên hiệu là Lạc Long Quân. Lạc Long Quân lấy con gái Đế Lai là Âu Cơ sinh ra một bọc một trăm trứng, một trăm trứng nở ra một trăm người con trai là tổ tiên của người Bách Việt.\n\n Một hôm nhà Vua bảo bà Âu Cơ: "Ta là giống Rồng, nàng là giống Tiên, thủy hỏa khắc nhau, chung hợp thật khó". Bèn từ biệt, chia năm chục người con theo mẹ lên núi , năm chục người con theo cha về phía Nam miền biển, phong cho con trưởng làm Hùng Vương nối ngôi.\n\nHùng Vương lên ngôi Vua, đặt quốc hiệu là Văn Lang, đóng đô ở Phong Châu (Bạch Hạc, Phú Thọ), chia nước ra làm 15 bộ.\n\nCác đời Vua sau đều gọi là Hùng Vương, có 18 đời vua Hùng Vương. Đặt các tướng văn gọi là Lạc Hầu, tướng võ gọi là Lạc Tướng, con trai vua gọi là Quan Lang, con gái Vua gọi là Mỵ Nương, các quan nhỏ gọi là Bồ Chính.\n\nNhà nước Văn Lang của các Vua Hùng là nhà nước phôi thai đầu tiên của Việt Nam, còn rất đơn giản, mặc dù mới hình thành nhưng đã cố kết được lòng người. Từ tình cảm cộng đồng dẫn đến ý thức cộng đồng, thể hiện rõ tình đồng bào ruột thịt. Họ bước đầu hiểu được mối quan hệ giữa thiên nhiên và con người, thấy được sức mạnh của cộng đồng trong việc làm thủy lợi, trao đổi sản phẩm và đấu tranh giữ gìn bản làng, đất nước.\n\nThời đại Hùng Vương có hai truyền thuyết được loan truyền mãi trong dân gian thể hiện rõ tinh thần đoàn kết của cộng đồng các dân tộc Việt.',
    description2: "",
    description3: "",
    description4: "",
    description5: "",
  },
  {
    idHistory: 2,
    title: "Âu Lạc & Nam Việt",
    description:
      "Theo hai bộ sử ký Đại Việt sử ký toàn thư (viết ở thế kỷ 15) và Đại Việt sử lược (viết ở thế kỷ 13), thì nhà nước Âu Lạc được Thục Phán (thủ lĩnh bộ tộc Âu Việt) thành lập vào năm 258 TCN sau khi đánh bại vị vua Hùng cuối cùng của nước Văn Lang, ông lên ngôi và lấy niên hiệu là An Dương Vương.\n\nAn Dương Vương sát nhập lãnh thổ của Văn Lang và lãnh thổ của bộ tộc mình (Âu Việt) và hình thành nên một nhà nước mới là Âu Lạc (kết hợp giữa người Âu Việt và người Lạc Việt)\n\nLãnh thổ Âu Lạc gồm lãnh cũ của bộ tộc Âu Việt ở phía bắc, mà ngày nay là một phần phía nam tỉnh Quảng Tây (Trung Quốc) và lãnh thổ của Văn Lang ở miền bắc Việt Nam. Âu Lạc có ranh giới phía bắc là sông Tả Giang (Quảng Tây) đến phía nam là dãy núi Hoành Sơn ở Hà Tĩnh hiện nay.",
    subTitle1: "Kỷ Nhà Thục",
    description1:
      "Thục Phán thủ lĩnh của người Âu Việt (phía Bắc nước Văn Lang) hợp nhất với nước Văn Lang của người Lạc Việt, xưng là An Dương Vương đặt quốc hiệu là nước Âu Lạc, đóng đô tại Cổ Loa (Đông Anh, Hà Nội).\n\nNăm 218 TCN, Tần Thủy Hoàng huy động 50 vạn quân, chia làm 5 đạo, đi chinh phục Bách Việt, chỉ huy đạo quân Tần là viên tướng lừng danh Đồ Thư. Các Lạc Tướng đã suy tôn Thục Phán là lãnh tụ chung để chỉ huy cuộc kháng chiến chống quân Tần. Người Việt làm chiến tranh du kích, vườn không nhà trống, bền bỉ kháng chiến suốt gần 10 năm, đợi khi quân Tần lâm vào tình trạng mệt mỏi, chán nản và khổ sở vì thiếu lương thực và ốm đau nhiều vì không hợp thủy thổ, lúc đó Thục Phán mới tổ chức phản công quân Tần, bắn chết Đồ Thư. Mất tướng chỉ huy, quân Tần mở đường máu tháo chạy về nước.\n\nSau chiến công vĩ đại đánh thắng 50 vạn quân Tần, An Dương Vương tổ chức xây thành Cổ Loa. Thành có 9 vòng, chu vi vòng ngoài 8km, vòng giữa 6,5 km, vòng trong cùng 1,6 km.\n\nVới vị trí thuận lợi, với cách bố trí thành có 9 lớp, xoáy trôn ốc, thành cao, hào sâu, có các ụ cao khô vượt ra ngoài lũy để có thể từ cao bắn xuống, với vũ khí nỏ thần và những mũi tên đồng lợi hại, sức mạnh quân sự tổng hợp của thành Cổ Loa làm cho quân thù khiếp sợ thể hiện trí tuệ quân sự tuyệt vời của tổ tiên ta. Ở ngoại thành Hà Nội ngày nay, vẫn còn thấy dấu tích 3 lớp thành Cổ Loa thời An Dương Vương.",

    description2: "",

    description3: "",
    description4: "",
    description5: "",
  },
  {
    idHistory: 3,
    title: "Bắc thuộc lần I",
    description:
      "Thời kỳ Bắc thuộc lần thứ nhất trong lịch sử Việt Nam kéo dài từ năm 218 TCN hoặc 179 TCN hoặc 111 TCN đến năm 39, dưới sự cai trị của phong kiến Trung Quốc.",
    subTitle1: "Kỷ Thuộc Tây Hán",
    description1:
      "Tân Mùi, [110 TCN], (Hán Nguyên Phong năm thứ 1). Nước Việt ta đã thuộc về nhà Hán. Nhà Hán cho Thạch Đái làm Thái Thú 9 quận. (Chế độ nhà Hán lấy châu lãnh quận, trừ hai quận Châu Nhai, Đạm Nhĩ đều ở giữa biển, còn 7 quận thuộc về Giao Châu, Đái làm châu Thái thú63. Thời Tây Hán, trị sở của Thái Thú đặt tại Long Uyên, tức là Long Biên, thời Đông Hán đặt tại Mê Linh tức là Yên Lăng).",
    subTitle2: "Triệu Vũ Vương - Triệu Đà",
    description2:
      "Họ Triệu, nhân lúc nhà Tần suy loạn, giết trưởng lại Tần, chiếm giữ đất Lĩnh Nam, xưng đế, đòi ngang với nhà Hán, hưởng nước truyền ngôi 100 năm mới mất, cũng là bậc vua anh hùng.\n\nHọ Triệu, tên húy là Đà, người huyện Chân Định nước Hán, đóng đô ở Phiên Ngung (nay ở tỉnh Quảng Đông).\n\nGiáp Ngọ, năm thứ 1 [207 TCN] , (Tần Nhị Thế năm thứ 3). Vua chiếm lấy đất Lâm Ấp và Tượng Quận, tự lập làm Nam Việt Vương.",
    subTitle3: "Triệu Văn Vương - Triệu Hồ",
    description3:
      "Triệu Văng Vương Tên húy là Hồ, con trai Trọng Thủy, cháu Vũ Đế. Vua lấy nghĩa để cảm nước láng giềng, đánh lui địch, yên biên cảnh, cũng gọi là bậc vua có ý muốn thịnh trị vậy.\n\nBính Ngọ, năm thứ 2 [135 TCN], (Hán Kiến Nguyên năm thứ 6). Mùa thu, tháng 8, có sao Chổi mọc ở phương đông, đuôi dài hết trời.\n\nMân Việt Vương Sính xâm lấn biên ấp nước ta. Vua giữ ước với nhà Hán, không tự tiện dấy quân, sai người đem thư nói việc đó với nhà Hán. Nhà Hán khen là nghĩa, vì vua mà phát đại binh, sai Vương Khôi xuất quân từ Dự Chương, Hàn An Quốc xuất quân từ Cối Kê, để đánh Mân Việt.",
    subTitle4: "Triệu Minh Vương - Triệu Anh Tề",
    description4:
      "Minh Vương ở ngôi 12 năm. Vua không cẩn thận mối vợ chồng, gây thành loạn cho quốc gia, không có gì đáng khen.\n\nĐinh Tỵ, năm thứ 1 [124 TCN], (Hán Nguyên Sóc năm thứ 5). Lấy Lữ Gia làm Thái phó.\n\nKỷ Mùi, năm thứ 3 [122 TCN], (Hán Nguyên Thú năm thứ 1). Mùa hạ, tháng 5, ngày 30, nhật thực.\n\nNhâm Tuất, năm thứ 6 [119 TCN], (Hán Nguyên Thú năm thứ 4). Mùa xuân, sao Chổi mọc ở phía đông bắc. Mùa hạ, sao Chổi dài mọc [12b] ở phương tây.\n\nẤt Sửu, năm thứ 9 [116 TCN], (Hán Nguyên Đỉnh năm thứ 1).\n\nMậu Thìn, năm thứ 12 [113 TCN], (Hán Nguyên Đỉnh năm thứ 4). Trước kia vua làm thế tử, sang làm con tin cho nhà Hán ở Trường An, lấy con gái người họ Cù ở Hàm Đan, sinh con tên là Hưng. Đến khi lên ngôi, giấu ấn của tiên đế đi, dâng thư sang nhà Hán xin lập Cù thị làm hoàng hậu, Hưng làm thế tử. Nhà Hán mấy lần sai sứ giả sang khuyên vua vào chầu. Vua sợ vào yết kiến phải theo pháp độ nhà Hán ngang với các chư hầu ở trong, cố ý cáo ốm không đi, bèn sai con là Thứ công vào làm con tin. Năm ấy vua mất, thụy là Minh Vương. Con là Hưng nối ngôi.",
    subTitle5: "Triệu Ai Vương - Triệu Hưng",
    description5:
      "Ở ngôi 1 năm.\n\nNăm ấy, vua đã lên ngôi, tôn mẹ là Cù thị là thái hậu.\n\nTrước kia, thái hậu chưa lấy Minh Vương, đã từng thông dâm với An Quốc Thiếu Quý người Bá Lăng. An Quốc là họ, Thiếu Quý là tên. Năm ấy nhà Hán sai An Quốc Thiếu Quý sang dụ vua và thái hậu vào chầu, như đối với các chư hầu ở trong, lại sai biện sĩ là bọn Gián nghị đại phu Chung Quân tuyên dụ, dũng sĩ là bọn Ngụy Thần giúp việc, vệ úy Lộ Bác Đức đem quân đóng ở Quế Dương để đợi sứ giả. Khi ấy vua còn ít tuổi, Cù hậu là người Hán, Thiếu Quý đến, lại tư thông. Người nước biết, phần nhiều không theo thái hậu. Thái hậu sợ loạn nổi, muốn dựa uy nhà Hán, nhiều lần khuyên vua và các quan xin nội phụ nhà Hán. Bèn nhờ sứ nhà Hán dâng thư, xin theo như các chư hầu ở trong, cứ 3 năm một lần vào chầu, triệt bỏ cửa quan ở biên giới. Vua Hán bằng lòng, ban cho vua và tướng Lữ Gia ấn bằng bạc và các ấn nội sử, trung úy, thái phó, còn các chức khác được tự đặt lấy. Bỏ hình phạt cũ thích chữ, cắt mũi, dùng pháp luật nhà Hán như các chư hầu ở trong. Các sứ giả đều ở lại để trấn giữ vỗ về.",
  },
  {
    idHistory: 4,
    title: "Trưng Nữ Vương",
    description:
      "Hai Bà Trưng (40 - 43) là thời kỳ xen giữa Bắc thuộc lần 1 và Bắc thuộc lần 2 trong lịch sử Việt Nam. Đây là tên gọi chung của hai chị em Trưng Trắc và Trưng Nhị, là anh hùng dân tộc của người Việt, những thủ lĩnh khởi binh chống lại nhà Đông Hán của Trung Quốc, lập ra một quốc gia với kinh đô tại Mê Linh và tự phong là Nữ vương.",
    subTitle1: "Hai Bà Trưng",
    description1:
      "Trưng Vương tên húy là Trắc, họ Trưng. Nguyên là họ Lạc, con gái của Lạc tướng huyện Mê Linh, Phong Châu, vợ của Thi Sách ở huyện Chu Diên. (Thi Sách cũng là con Lạc tướng, con hai nhà tướng kết hôn với nhau. Sách Cương mục tập lãm lấy Lạc làm họ là lầm). Đóng đô ở Mê Linh.\n\nCanh Tý, năm thứ 1 [40], (Hán Kiến Vũ năm thứ 16). Mùa xuân, tháng 2, vua khổ vì Thái thú Tô Định dùng pháp luật trói buộc, lại thù Định giết chồng mình, mới cùng với em gái là Nhị nổi binh đánh hãm trị sở ở châu. Định chạy về nước. Các quận Nam Hải, Cửu Chân, Nhật Nam, Hợp Phố đều hưởng ứng, lấy được [2b] 65 thành ở Lĩnh Nam, tự lập làm vua, mới xưng là họ Trưng.",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 5,
    title: "Bắc thuộc lần II",
    description:
      "Thời kỳ Bắc thuộc lần thứ hai trong lịch sử Việt Nam kéo dài từ năm 43 đến năm 543. Thời kỳ này bắt đầu khi Mã Viện theo lệnh Hán Quang Vũ Đế nhà Đông Hán đánh chiếm lại bộ Giao Chỉ từ tay Trưng Vương, kéo dài đến khi Lý Bí khởi binh đánh đuổi thứ sử[1] nhà Lương là Tiêu Tư năm 542 rồi lập ra nước Vạn Xuân năm 544.\n\nThời kỳ Bắc thuộc lần thứ 2 kéo dài khoảng 500 năm.",
    subTitle1: "Kỷ Thuộc Đông Hán",
    description1:
      'Quý Mão, [Trưng Vương, năm thứ 4], (Hán Kiến Vũ năm thứ 19). Mùa xuân, tháng giêng, Trưng Nữ Vương cùng em gái là Nhị chống cự lại với quân nhà Hán, thế cô, đều thua chết. Mã Viện đuổi theo đánh quân còn sót là bọn Đô Dương. Đến huyện Cư Phong thì [bọn Đô Dương] đầu hàng, [Viện] bèn dựng cột đồng làm giới hạn cuối cùng của nhà Hán. (Cột đồng tương truyền ở trên động Cổ Lâu châu Khâm. Viện có câu thề: "Cột đồng gãy thì Giao Châu diệt". Người Việt ta đi qua dưới cột ấy, thường lấy đá chất vào, thành như gò đống, vì sợ cột ấy gãy. Mã Tổng nhà Đường lại dựng hai cột đồng ở chỗ cũ của nhà Hán ghi công đức của Mã Viện để tỏ ra mình là dòng dõi của Phục Ba, nay chưa rõ ở chỗ nào. Hai sông Tả Giang, Hữu Giang mỗi nơi có một cột). Viện thấy huyện Tây Vu có 3 vạn 3 nghìn hộ, xin chia làm hai huyện Phong Kê và Vọng Hải, vua Hán nghe theo. Viện lại đắp thành Kiển Giang ở huyện Phong Khê. Thành đắp tròn như hình cái kén, cho nên lấy [chữ Kiển]làm tên. Nước Việt ta lại thuộc vào nhà Hán. Ba năm sau, Viện trở về. Người địa phương thương mến Trưng Nữ Vương, làm đền thờ phụng (đền ở xã Hát Giang, huyện Phúc Lộc, ở đất cũ thành Phiên Ngung cũng có).',
    subTitle2: "Kỷ Sĩ Vương - Sĩ Nhiếp",
    description2:
      "Sĩ Vương họ Sĩ, tên húy là Nhiếp, tự là Ngạn Uy, người huyện Quảng Tín, quận Thương Ngô. Tổ tiên người Vấn Dương nước Lỗ, hồi loạn Vương Mãng ở Bắc triều, tránh sang ở đất Việt ta, đến vương là sáu đời. Cha là Tứ, thời Hán Hoàn Đế làm Thái thú Nhật Nam. Khi còn ít tuổi, vương du học ở kinh đô nhà Hán, theo học Lưu Tử Kỳ người Dĩnh Xuyên, chuyên trị sách Tả thị Xuân Thu, có làm chú giải: được cử hiếu liêm, bổ làm Thượng thư lang, vì việc công bị miễn chức; hết tang cha, lại được cử mậu tài, bổ làm Huyện lệnh Vu Dương, đổi làm Thái thú Giao Châu, được tước Long Độ Đình hầu, đóng đô ở Liên Lâu (tức là Long Biên). Sau nhà Trần truy phong làm Thiên Cảm Gia Ứng Vũ Đại Vương.\n\nĐinh Mão, năm thứ 1 [187], (Hán Trung Bình năm thứ 4). Vương có ba em trai tên là Nhất, Vĩ và Vũ. Bấy giờ Thứ sử Chu [8b] Phù bị giặc Di giết chết, châu quận rối loạn, vương bèn dâng biểu cử Nhất làm Thái thú Hợp Phố, Vĩ làm Thái thú Cửu Chân, Vũ làm Thái thú Nam Hải. Vương độ lượng khoan hậu, khiêm tốn, kính trọng kẻ sĩ, người trong nước yêu mến, đều gọi là vương. Danh sĩ nhà Hán tránh nạn sang nương tựa có hàng trăm người.",
    subTitle3: "Kỷ thuộc Đông Ngô",
    description3:
      "Đinh Mùi, [227], (Hán Kiến Hưng năm thứ 5; Ngô Hoàng Vũ năm thứ 6), Vua Ngô nghe tin Sĩ Nhiếp mất, thấy Giao Châu ở xa cách, mới chia từ quận Hợp Phố trở về bắc thuộc vào Quảng Châu, cho Lữ Đại làm Thứ sử; từ quận Hợp Phố trở về nam thuộc vào Giao Châu, cho Đái Lương làm Thứ sử. Lại sai Trần Thì làm Thái thú thay Sĩ Nhiếp. Đại ở lại Nam Hải. Lương và Thì cùng lên đường. Đến Hợp Phố nghe tin ở Giao Châu con Sĩ Nhiếp là Huy đã tự làm Thái thú, đem tông binh ra chống cự. (Cuối thời nhà Hán, tôn thất nổi loạn, người Nam cũng tụ họp họ hàng làm binh để tự vệ, cho nên gọi là tông binh). Lương ở lại Hợp Phố. Thuộc lại của Sĩ Nhiếp là Hoàn Lân cúi đầu can Huy, xin đón Lương, Huy giận đánh chết Lân.\n\nSử thần Ngô Sĩ Liên nói: Từ xưa hễ giết bề tôi can ngăn thì chưa từng không mất nước. Nước Trần giết [1b] Tiết Dã, nước Tề giết Cô Huyên, việc nước Trần, nước Tề đáng làm gương soi, lấy đó làm răn. Thế mà còn có người giết bề tôi căn ngăn như Sĩ Huy, nối nghiệp chưa kịp quay gót mà đã phải chết là đáng lắm.",
    subTitle4: "Thuộc Lưỡng Tấn",
    description4:
      "Giáp Thân, [264], (Ngụy Tào Hoán Hàm Hy năm thứ 1, Ngô Tôn Hạo Nguyên Hưng năm thứ 1).\n\nMùa thu, tháng 7, nhà Ngô tách Giao Châu, đặt Quảng Châu. Bấy giờ Ngô đã phụ vào Tấn. Nhà Tấn cho Lữ Hưng làm An Nam tướng quân đô đốc Giao Châu chư quân sự, cho Nam Trung giáp quân là Hoắc Dặc xa lĩnh Thứ sử Giao Châu, cho được tùy nghi tuyển dụng trưởng lại.",
    subTitle5: "Thuộc Tống, Tề, Lương",
    description5:
      "Từ thời Lưỡng Tấn tới thời Nam Bắc triều, tuy có sự thay đổi triều đại và biến động nhiều ở trung nguyên nhưng Giao châu chỉ có những biến động quân sự, không có nhiều biến động về chính trị.\n\nTại miền bắc, các tộc Ngũ Hồ vào xâm chiếm và cai trị, các triều đại Đông Tấn (317-420), Lưu Tống (420-479), Nam Tề (479-502), Lương (502-557) nối nhau cai trị ở miền nam và giữ được quyền quản lý Giao châu không bị gián đoạn, thay đổi như cuối thời Đông Hán và Tam Quốc. Những cuộc nổi dậy của người Việt chỉ kéo dài một thời gian đều bị dẹp; những cuộc xâm lấn của Lâm Ấp từ phía nam cũng nhanh chóng bị đẩy lùi; một số lực lượng nổi dậy chống triều đình chạy sang Giao châu cũng nhanh chóng bị đánh bại.",
  },
  {
    idHistory: 6,
    title: "Nhà Lý & Nhà Triệu",
    description:
      "Nhà Tiền Lý (544-602) là một triều đại trong lịch sử Việt Nam, gắn liền với quốc hiệu Vạn Xuân. Nhà Tiền Lý kéo dài 58 năm, tổng cộng 3 đời vua, trong đó có 2 vua họ Lý và 1 vua họ Triệu cũng được tính gộp vào nhà Tiền Lý, tương tự như Dương Tam Kha trong nhà Ngô sau đó.",
    subTitle1: "Lý Nam Đế - Lý Bí",
    description1:
      "Lý Bôn tức Lý Bí, quê ở Long Hưng (Thái Bình), sinh ngày 12 tháng 9 năm Quý Mùi (17/10/503), là con hào trưởng Lý Toản, mẹ là Lê Thị Oánh người Ái Châu (Thanh Hoá), 5 tuổi bố mất, 7 tuổi mẹ mất, phải ở với chú ruột. Vị pháp tổ thiền sư thấy khôi ngô tuấn tú xin làm con nuôi đưa về chùa Linh Bảo nuôi dạy. Hơn mười năm đèn sách chuyên cần, lại được vị thiền sư hết lòng dạy bảo, Lý Bí trở thành người học rộng hiểu sâu, ít người sánh kịp. Nhờ có tài kiêm văn võ, Lý Bí được tôn làm thủ lĩnh địa phương.\n\nThấy nhân dân ta vô cùng thống khổ dưới sự đô hộ tàn ác của Tiêu Tư. Tháng 1 năm 542 Lý Bí lãnh đạo nhân dân khởi binh tấn công quân Lương. Thứ sử Tiêu Tư khiếp sợ bỏ chạy về nước. Chưa đầy 3 tháng Lý Bí đã chiếm được hầu hết các quận, huyện và thành Long Biên. Nhà Lương sai tướng đem quân sang phản công chiếm lại, Lý Bí đã cho quân mai phục đánh tan bọn xâm lược.\n\nĐầu năm 543, vua Lương lại huy động binh mã sang xâm lược nước ta một lần nữa. Lý Bí chủ động đem quân đón đánh giặc ở bán đảo Hợp Phố, quân Lương bị tiêu diệt gần hết. Tháng Hai năm Giáp Tý - 544, Lý Bí lên ngôi Hoàng đế lấy hiệu là Lý Nam Đế, đặt tên nước là Vạn Xuân, đóng đô ở Long Biên.",
    subTitle2: "Triệu Việt Vương - Triệu Quang Phục",
    description2:
      "Triệu Quang Phục là con Triệu Túc, Tù trưởng ở Chu Diên (Hưng Yên). Khi được Lý Nam Đế trao quyền lãnh đạo cuộc kháng chiến chống quân Lương, ông đưa quân về Dạ Trạch (bãi Màn Trò, Hưng Yên) là một vùng đồng lầy rộng mênh mông, lau sậy um tùm, ở giữa có một bãi đất cao khô ráo để đóng quân. Ông cho quân lính vừa sản xuất lương thực, vừa tiếp tục cuộc kháng chiến lâu dài. Đêm đêm nghĩa quân kéo ra đánh các đồn địch, làm cho lực lượng địch bị tiêu hao và mất ăn, mất ngủ.\n\nNgày 13/4/548, Triệu Quang Phục lên ngôi vua, xưng là Triệu Việt Vương, dân gian gọi ông là Dạ Trạch Vương.\n\nNăm 550, từ căn cứ Dạ Trạch ông tiến quân ra đánh giết được tướng giặc là Dương San, thu lại được thành Long Biên.",
    subTitle3: "Hậu Lý Nam Đế - Lý Phật Tử",
    description3:
      "Diệt xong Triệu Việt Vương, Lý Phật Tử xưng là hậu Lý Nam Đế, đóng đô ở Phong Châu (Bạch Hạc - Phú Thọ).\n\nTrong lúc Lý Phật Tử làm vua ở nước ta, thì bên Trung Quốc Tuỳ Văn Đế dẹp yên được Nam Bắc triều, thống nhất được đất nước Trung Hoa.\n\nNăm Nhâm Tuất (602) nhà Tuỳ sai danh tướng Lưu Phương đem quân sang xâm lược nước ta.",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 7,
    title: "Bắc thuộc lần III",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 8,
    title: "Thời kỳ xây nền tự chủ",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 9,
    title: "Nhà Ngô",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 10,
    title: "Nhà Đinh",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 11,
    title: "Nhà Tiền Lê",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 12,
    title: "Nhà Lý",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 13,
    title: "Nhà Trần",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 14,
    title: "Nhà Hồ",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 15,
    title: "Nhà Hậu Trần",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 16,
    title: "Bắc thuộc lần IV",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 17,
    title: "Nhà Hậu Lê",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 18,
    title: "Nam Bắc Triều",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 19,
    title: "Trịnh Nguyễn Phân Tranh",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 20,
    title: "Nhà Tây Sơn",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 21,
    title: "Nhà Nguyễn",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 22,
    title: "Pháp Thuộc",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 23,
    title: "Việt Nam Dân Chủ Cộng Hòa",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
  {
    idHistory: 24,
    title: "Cộng hòa xã hội chủ nghĩa Việt Nam",
    description: "",
    subTitle1: "",
    description1: "",
    subTitle2: "",
    description2: "",
    subTitle3: "",
    description3: "",
    subTitle4: "",
    description4: "",
    subTitle5: "",
    description5: "",
  },
];

export default historyData;
